FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 设置阿里云镜像源
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list

# 安装系统依赖（这一层变化极少，优先缓存）
RUN apt-get update -y --fix-missing && \
    apt-get install -y --no-install-recommends \
        python3.11 python3.11-dev python3.11-distutils \
        git build-essential curl wget git-lfs sox libsox-dev && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    git lfs install

WORKDIR /workspace

# 先复制依赖配置文件（仅当这些文件变化时，才会重新执行后续依赖安装）
COPY requirements.worker.txt ./
COPY LightX2V ./

# 安装基础依赖
RUN pip install -v -r ./requirements.worker.txt --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/
RUN pip install -v -e ./LightX2V --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/

# 安装推理加速
RUN pip install -v flash-attn --no-build-isolation --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/

# 复制其他项目文件（代码文件变化不影响依赖层缓存）
COPY . .

# 复制配置文件
COPY .env.docker .env

ENV LOG_LEVEL=INFO

CMD ["python", "start_worker.py"]